// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VN2Anki.Data;

#nullable disable

namespace VN2Anki.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310195722_AddArchitectureToVn")]
    partial class AddArchitectureToVn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("VN2Anki.Models.Entities.SessionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardsMined")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharactersRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EffectiveDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawFilePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VisualNovelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VisualNovelId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("VN2Anki.Models.Entities.VisualNovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Architecture")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("EffectiveTimePlayedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutablePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPlayed")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCardsMined")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCharactersRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTimePlayedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VndbId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VisualNovels");
                });

            modelBuilder.Entity("VN2Anki.Models.Entities.SessionRecord", b =>
                {
                    b.HasOne("VN2Anki.Models.Entities.VisualNovel", "VisualNovel")
                        .WithMany("Sessions")
                        .HasForeignKey("VisualNovelId");

                    b.Navigation("VisualNovel");
                });

            modelBuilder.Entity("VN2Anki.Models.Entities.VisualNovel", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
