//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VN2Anki.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VN2Anki.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Settings.
        /// </summary>
        public static string BtnApplySettings {
            get {
                return ResourceManager.GetString("BtnApplySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind Current Session.
        /// </summary>
        public static string BtnBindCurrentSession {
            get {
                return ResourceManager.GetString("BtnBindCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END SESSION.
        /// </summary>
        public static string BtnEndSession {
            get {
                return ResourceManager.GetString("BtnEndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HISTORY.
        /// </summary>
        public static string BtnHistory {
            get {
                return ResourceManager.GetString("BtnHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERLAY.
        /// </summary>
        public static string BtnOverlay {
            get {
                return ResourceManager.GetString("BtnOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Already Registered.
        /// </summary>
        public static string BtnProcessAlreadyRegistered {
            get {
                return ResourceManager.GetString("BtnProcessAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECORD.
        /// </summary>
        public static string BtnRecord {
            get {
                return ResourceManager.GetString("BtnRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE AND CLOSE.
        /// </summary>
        public static string BtnSaveClose {
            get {
                return ResourceManager.GetString("BtnSaveClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START BUFFER.
        /// </summary>
        public static string BtnStartBuffer {
            get {
                return ResourceManager.GetString("BtnStartBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP BUFFER.
        /// </summary>
        public static string BtnStopBuffer {
            get {
                return ResourceManager.GetString("BtnStopBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card updated!.
        /// </summary>
        public static string CardUpdated {
            get {
                return ResourceManager.GetString("CardUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anki.
        /// </summary>
        public static string HeaderAnki {
            get {
                return ResourceManager.GetString("HeaderAnki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string HeaderConfig {
            get {
                return ResourceManager.GetString("HeaderConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string HeaderControls {
            get {
                return ResourceManager.GetString("HeaderControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string HeaderIcon {
            get {
                return ResourceManager.GetString("HeaderIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Sessions.
        /// </summary>
        public static string HeaderLastSessions {
            get {
                return ResourceManager.GetString("HeaderLastSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string HeaderSettings {
            get {
                return ResourceManager.GetString("HeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string HeaderStatus {
            get {
                return ResourceManager.GetString("HeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Statistics.
        /// </summary>
        public static string HeaderTotalStats {
            get {
                return ResourceManager.GetString("HeaderTotalStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Time.
        /// </summary>
        public static string LabelActiveTime {
            get {
                return ResourceManager.GetString("LabelActiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFK Time.
        /// </summary>
        public static string LabelAfkTime {
            get {
                return ResourceManager.GetString("LabelAfkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Back.
        /// </summary>
        public static string LabelBack {
            get {
                return ResourceManager.GetString("LabelBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string LabelCharacters {
            get {
                return ResourceManager.GetString("LabelCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🅰 CHARS.
        /// </summary>
        public static string LabelChars {
            get {
                return ResourceManager.GetString("LabelChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  c/h.
        /// </summary>
        public static string LabelCharsPerHourSuffix {
            get {
                return ResourceManager.GetString("LabelCharsPerHourSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chars.
        /// </summary>
        public static string LabelCharsReadFormat {
            get {
                return ResourceManager.GetString("LabelCharsReadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string LabelContent {
            get {
                return ResourceManager.GetString("LabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Delete.
        /// </summary>
        public static string LabelDelete {
            get {
                return ResourceManager.GetString("LabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️ Edit.
        /// </summary>
        public static string LabelEdit {
            get {
                return ResourceManager.GetString("LabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Visual Novel.
        /// </summary>
        public static string LabelEditVn {
            get {
                return ResourceManager.GetString("LabelEditVn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string LabelEvent {
            get {
                return ResourceManager.GetString("LabelEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Path.
        /// </summary>
        public static string LabelExecutablePath {
            get {
                return ResourceManager.GetString("LabelExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string LabelFrequency {
            get {
                return ResourceManager.GetString("LabelFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph: {0}.
        /// </summary>
        public static string LabelGraphTypeFormat {
            get {
                return ResourceManager.GetString("LabelGraphTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeatMap.
        /// </summary>
        public static string LabelHeatMap {
            get {
                return ResourceManager.GetString("LabelHeatMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏱ HOURS.
        /// </summary>
        public static string LabelHours {
            get {
                return ResourceManager.GetString("LabelHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data for the graph..
        /// </summary>
        public static string LabelInsufficientGraphData {
            get {
                return ResourceManager.GetString("LabelInsufficientGraphData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookups.
        /// </summary>
        public static string LabelLookups {
            get {
                return ResourceManager.GetString("LabelLookups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mined.
        /// </summary>
        public static string LabelMined {
            get {
                return ResourceManager.GetString("LabelMined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mined Words.
        /// </summary>
        public static string LabelMinedWords {
            get {
                return ResourceManager.GetString("LabelMinedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No words mined in this session..
        /// </summary>
        public static string LabelNoMinedWords {
            get {
                return ResourceManager.GetString("LabelNoMinedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Sentences.
        /// </summary>
        public static string LabelNumSentences {
            get {
                return ResourceManager.GetString("LabelNumSentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overhead.
        /// </summary>
        public static string LabelOverhead {
            get {
                return ResourceManager.GetString("LabelOverhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Play.
        /// </summary>
        public static string LabelPlay {
            get {
                return ResourceManager.GetString("LabelPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Pace (Gaussian).
        /// </summary>
        public static string LabelReadingPaceGaussian {
            get {
                return ResourceManager.GetString("LabelReadingPaceGaussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENT SESSIONS.
        /// </summary>
        public static string LabelRecentSessions {
            get {
                return ResourceManager.GetString("LabelRecentSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LabelSave {
            get {
                return ResourceManager.GetString("LabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string LabelSecondsSuffix {
            get {
                return ResourceManager.GetString("LabelSecondsSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence History.
        /// </summary>
        public static string LabelSentenceHistory {
            get {
                return ResourceManager.GetString("LabelSentenceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentences.
        /// </summary>
        public static string LabelSentences {
            get {
                return ResourceManager.GetString("LabelSentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 SPEED.
        /// </summary>
        public static string LabelSpeed {
            get {
                return ResourceManager.GetString("LabelSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string LabelSummary {
            get {
                return ResourceManager.GetString("LabelSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string LabelTime {
            get {
                return ResourceManager.GetString("LabelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        public static string LabelTotalTime {
            get {
                return ResourceManager.GetString("LabelTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VNDB ID (Ex: v1143).
        /// </summary>
        public static string LabelVndbIdHint {
            get {
                return ResourceManager.GetString("LabelVndbIdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasted Time.
        /// </summary>
        public static string LabelWastedTime {
            get {
                return ResourceManager.GetString("LabelWastedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app needs to be restarted for the language change to take effect..
        /// </summary>
        public static string LangRestartNow {
            get {
                return ResourceManager.GetString("LangRestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnkiConnect URL:.
        /// </summary>
        public static string LblAnkiUrl {
            get {
                return ResourceManager.GetString("LblAnkiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Field:.
        /// </summary>
        public static string LblAudioField {
            get {
                return ResourceManager.GetString("LblAudioField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Format.
        /// </summary>
        public static string LblAudioQuality {
            get {
                return ResourceManager.GetString("LblAudioQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Source:.
        /// </summary>
        public static string LblAudioSource {
            get {
                return ResourceManager.GetString("LblAudioSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Launch Hooker:.
        /// </summary>
        public static string LblAutoLaunchHooker {
            get {
                return ResourceManager.GetString("LblAutoLaunchHooker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string LblBottom {
            get {
                return ResourceManager.GetString("LblBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Min-Height (px):.
        /// </summary>
        public static string LblBoxMinHeight {
            get {
                return ResourceManager.GetString("LblBoxMinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Width (%):.
        /// </summary>
        public static string LblBoxWidth {
            get {
                return ResourceManager.GetString("LblBoxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser:.
        /// </summary>
        public static string LblBrowser {
            get {
                return ResourceManager.GetString("LblBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string LblCenter {
            get {
                return ResourceManager.GetString("LblCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string LblClipboard {
            get {
                return ResourceManager.GetString("LblClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck:.
        /// </summary>
        public static string LblDeck {
            get {
                return ResourceManager.GetString("LblDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displacement &amp; Margins:.
        /// </summary>
        public static string LblDisplacementMargins {
            get {
                return ResourceManager.GetString("LblDisplacementMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURATION.
        /// </summary>
        public static string LblDuration {
            get {
                return ResourceManager.GetString("LblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Dynamic Timeout (Recommended).
        /// </summary>
        public static string LblDynamicTimeout {
            get {
                return ResourceManager.GetString("LblDynamicTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Yomitan Bridge (Proxy).
        /// </summary>
        public static string LblEnableYomitanBridge {
            get {
                return ResourceManager.GetString("LblEnableYomitanBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Path (.exe).
        /// </summary>
        public static string LblExePath {
            get {
                return ResourceManager.GetString("LblExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore similar phrases (Anti-spam).
        /// </summary>
        public static string LblFilterSimilar {
            get {
                return ResourceManager.GetString("LblFilterSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Hook Source:.
        /// </summary>
        public static string LblHookSource {
            get {
                return ResourceManager.GetString("LblHookSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X (Horiz):.
        /// </summary>
        public static string LblHorizX {
            get {
                return ResourceManager.GetString("LblHorizX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the textbox and press a key combination to bind. Press ESC or DEL to clear..
        /// </summary>
        public static string LblHotkeyHint {
            get {
                return ResourceManager.GetString("LblHotkeyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Field:.
        /// </summary>
        public static string LblImageField {
            get {
                return ResourceManager.GetString("LblImageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Quality.
        /// </summary>
        public static string LblImageQuality {
            get {
                return ResourceManager.GetString("LblImageQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LblLanguage {
            get {
                return ResourceManager.GetString("LblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LunaTranslator Path:.
        /// </summary>
        public static string LblLunaPath {
            get {
                return ResourceManager.GetString("LblLunaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string LblNone {
            get {
                return ResourceManager.GetString("LblNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Type:.
        /// </summary>
        public static string LblNoteType {
            get {
                return ResourceManager.GetString("LblNoteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings on Startup.
        /// </summary>
        public static string LblOpenSettingsOnStartup {
            get {
                return ResourceManager.GetString("LblOpenSettingsOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string LblOriginal {
            get {
                return ResourceManager.GetString("LblOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Box BG:.
        /// </summary>
        public static string LblOverlayBg {
            get {
                return ResourceManager.GetString("LblOverlayBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color:.
        /// </summary>
        public static string LblOverlayFontColor {
            get {
                return ResourceManager.GetString("LblOverlayFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family:.
        /// </summary>
        public static string LblOverlayFontFamily {
            get {
                return ResourceManager.GetString("LblOverlayFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size:.
        /// </summary>
        public static string LblOverlayFontSize {
            get {
                return ResourceManager.GetString("LblOverlayFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Outline Color:.
        /// </summary>
        public static string LblOverlayOutlineColor {
            get {
                return ResourceManager.GetString("LblOverlayOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string LblPath {
            get {
                return ResourceManager.GetString("LblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VN2Anki - Settings.
        /// </summary>
        public static string LblSettingsWindow {
            get {
                return ResourceManager.GetString("LblSettingsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent Sync sessions automatically.
        /// </summary>
        public static string LblSilentSync {
            get {
                return ResourceManager.GetString("LblSilentSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold:.
        /// </summary>
        public static string LblSimilarityThreshold {
            get {
                return ResourceManager.GetString("LblSimilarityThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Limit:.
        /// </summary>
        public static string LblSlotLimit {
            get {
                return ResourceManager.GetString("LblSlotLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textractor Base Path:.
        /// </summary>
        public static string LblTextractorPath {
            get {
                return ResourceManager.GetString("LblTextractorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string LblLeft {
            get {
                return ResourceManager.GetString("LblLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string LblRight {
            get {
                return ResourceManager.GetString("LblRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text Horizontal Align:.
        /// </summary>
        public static string LblTextHorizontalAlign {
            get {
                return ResourceManager.GetString("LblTextHorizontalAlign", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text Vertical Align:.
        /// </summary>
        public static string LblTextVerticalAlign {
            get {
                return ResourceManager.GetString("LblTextVerticalAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness:.
        /// </summary>
        public static string LblThickness {
            get {
                return ResourceManager.GetString("LblThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (s):.
        /// </summary>
        public static string LblTimeout {
            get {
                return ResourceManager.GetString("LblTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string LblTop {
            get {
                return ResourceManager.GetString("LblTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Text Box Mode (Masking).
        /// </summary>
        public static string LblUseTextBoxMode {
            get {
                return ResourceManager.GetString("LblUseTextBoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y (Vert):.
        /// </summary>
        public static string LblVertY {
            get {
                return ResourceManager.GetString("LblVertY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Source:.
        /// </summary>
        public static string LblVideoSource {
            get {
                return ResourceManager.GetString("LblVideoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. VNDB Search (Romaji/English):.
        /// </summary>
        public static string LblVndbSearch {
            get {
                return ResourceManager.GetString("LblVndbSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Preview:.
        /// </summary>
        public static string LblWindowPreview {
            get {
                return ResourceManager.GetString("LblWindowPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSocket (Luna).
        /// </summary>
        public static string LblWsLuna {
            get {
                return ResourceManager.GetString("LblWsLuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSocket (Textractor).
        /// </summary>
        public static string LblWsTextractor {
            get {
                return ResourceManager.GetString("LblWsTextractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSocket URL:.
        /// </summary>
        public static string LblWsUrl {
            get {
                return ResourceManager.GetString("LblWsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yomitan Bridge Port (Requires Restart):.
        /// </summary>
        public static string LblYomitanBridgePort {
            get {
                return ResourceManager.GetString("LblYomitanBridgePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot perform Auto-Sync while a session is in progress.\nEnd the current session first..
        /// </summary>
        public static string MsgActionBlockedAutoSync {
            get {
                return ResourceManager.GetString("MsgActionBlockedAutoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot change or unbind the VN while a session is in progress.\nEnd the current session first..
        /// </summary>
        public static string MsgActionBlockedSession {
            get {
                return ResourceManager.GetString("MsgActionBlockedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string MsgAttention {
            get {
                return ResourceManager.GetString("MsgAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card updated!.
        /// </summary>
        public static string MsgCardUpdated {
            get {
                return ResourceManager.GetString("MsgCardUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Audio first!.
        /// </summary>
        public static string MsgConfigureAudioFirst {
            get {
                return ResourceManager.GetString("MsgConfigureAudioFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A session is active with &apos;{0}&apos;.\nDo you want to end it and start another with &apos;{1}&apos;?.
        /// </summary>
        public static string MsgConfirmChangeSession {
            get {
                return ResourceManager.GetString("MsgConfirmChangeSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End current session? Unsent slots will be lost..
        /// </summary>
        public static string MsgConfirmEndSession {
            get {
                return ResourceManager.GetString("MsgConfirmEndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You read some characters, but no Visual Novel is selected.\nDo you want to save this progress to history to bind it to a game later?.
        /// </summary>
        public static string MsgConfirmSaveOrphanSession {
            get {
                return ResourceManager.GetString("MsgConfirmSaveOrphanSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this session?.
        /// </summary>
        public static string MsgConfirmSessionDelete {
            get {
                return ResourceManager.GetString("MsgConfirmSessionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Visual Novel is bound to this session.\nDo you want to start tracking anyway?.
        /// </summary>
        public static string MsgConfirmStartTrackingWithoutVn {
            get {
                return ResourceManager.GetString("MsgConfirmStartTrackingWithoutVn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete &apos;{0}&apos;.\nThis will permanently remove {1} recorded sessions.\n\nDo you wish to continue?.
        /// </summary>
        public static string MsgConfirmVnDelete {
            get {
                return ResourceManager.GetString("MsgConfirmVnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We detected that &apos;{0}&apos; is running.\nDo you want to bind it and start the session now?.
        /// </summary>
        public static string MsgConfirmVnDetected {
            get {
                return ResourceManager.GetString("MsgConfirmVnDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty!.
        /// </summary>
        public static string MsgEmpty {
            get {
                return ResourceManager.GetString("MsgEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR!.
        /// </summary>
        public static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This executable is already being used by another game in the Library..
        /// </summary>
        public static string MsgExeAlreadyInUse {
            get {
                return ResourceManager.GetString("MsgExeAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ This executable is already registered as &apos;{0}&apos;..
        /// </summary>
        public static string MsgExeAlreadyRegistered {
            get {
                return ResourceManager.GetString("MsgExeAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable not found!.
        /// </summary>
        public static string MsgExeNotFound {
            get {
                return ResourceManager.GetString("MsgExeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid extension path or not found..
        /// </summary>
        public static string MsgInvalidExtensionPath {
            get {
                return ResourceManager.GetString("MsgInvalidExtensionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple running VNs detected.\nSelect which one you want to bind:.
        /// </summary>
        public static string MsgMultipleVnsDetected {
            get {
                return ResourceManager.GetString("MsgMultipleVnsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a VNDB result!.
        /// </summary>
        public static string MsgSelectVndbResult {
            get {
                return ResourceManager.GetString("MsgSelectVndbResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session linked: {0}.
        /// </summary>
        public static string MsgSessionLinked {
            get {
                return ResourceManager.GetString("MsgSessionLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics recalculated successfully!.
        /// </summary>
        public static string MsgStatsRecalculatedSuccess {
            get {
                return ResourceManager.GetString("MsgStatsRecalculatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media successfully added.
        /// </summary>
        public static string MsgSuccess {
            get {
                return ResourceManager.GetString("MsgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target window is closed! Open the game and try again..
        /// </summary>
        public static string MsgTargetWindowClosed {
            get {
                return ResourceManager.GetString("MsgTargetWindowClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Source empty! Select the video..
        /// </summary>
        public static string MsgVideoSourceEmpty {
            get {
                return ResourceManager.GetString("MsgVideoSourceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Visual Novel is already added to your Library!.
        /// </summary>
        public static string MsgVnAlreadyInLibrary {
            get {
                return ResourceManager.GetString("MsgVnAlreadyInLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout: Window did not appear..
        /// </summary>
        public static string MsgWindowTimeout {
            get {
                return ResourceManager.GetString("MsgWindowTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yomitan not found in the default Chrome/Edge directories..
        /// </summary>
        public static string MsgYomitanNotFound {
            get {
                return ResourceManager.GetString("MsgYomitanNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string StatusAdded {
            get {
                return ResourceManager.GetString("StatusAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready and connected to Anki..
        /// </summary>
        public static string StatusAnkiConnected {
            get {
                return ResourceManager.GetString("StatusAnkiConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anki not detected..
        /// </summary>
        public static string StatusAnkiError {
            get {
                return ResourceManager.GetString("StatusAnkiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Added.
        /// </summary>
        public static string StatusNotAdded {
            get {
                return ResourceManager.GetString("StatusNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing media.
        /// </summary>
        public static string StatusPreparing {
            get {
                return ResourceManager.GetString("StatusPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready. Configure sources and start buffer..
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔴 Recording Audio....
        /// </summary>
        public static string StatusRecordingAudio {
            get {
                return ResourceManager.GetString("StatusRecordingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Running....
        /// </summary>
        public static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ended and memory cleared..
        /// </summary>
        public static string StatusSessionEnded {
            get {
                return ResourceManager.GetString("StatusSessionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Stopped..
        /// </summary>
        public static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video connected! Ready to play..
        /// </summary>
        public static string StatusVideoConnected {
            get {
                return ResourceManager.GetString("StatusVideoConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Video disconnected! Buffer paused..
        /// </summary>
        public static string StatusVideoDisconnected {
            get {
                return ResourceManager.GetString("StatusVideoDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        public static string TabExtensions {
            get {
                return ResourceManager.GetString("TabExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook.
        /// </summary>
        public static string TabHook {
            get {
                return ResourceManager.GetString("TabHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string TabHotkeys {
            get {
                return ResourceManager.GetString("TabHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        public static string TabOverlay {
            get {
                return ResourceManager.GetString("TabOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive = Right, Negative = Left.
        /// </summary>
        public static string TipHorizX {
            get {
                return ResourceManager.GetString("TipHorizX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct path to LunaTranslator.exe.
        /// </summary>
        public static string TipLunaPath {
            get {
                return ResourceManager.GetString("TipLunaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder containing x86 and x64 subfolders.
        /// </summary>
        public static string TipTextractorPath {
            get {
                return ResourceManager.GetString("TipTextractorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin relative to Top or Bottom.
        /// </summary>
        public static string TipVertY {
            get {
                return ResourceManager.GetString("TipVertY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string TitleDuplicate {
            get {
                return ResourceManager.GetString("TitleDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Session Warning.
        /// </summary>
        public static string TitleEmptySessionWarning {
            get {
                return ResourceManager.GetString("TitleEmptySessionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string TitleHistoryWindow {
            get {
                return ResourceManager.GetString("TitleHistoryWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple VNs Detected.
        /// </summary>
        public static string TitleMultipleVnsDetected {
            get {
                return ResourceManager.GetString("TitleMultipleVnsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Orphan Session?.
        /// </summary>
        public static string TitleSaveOrphanSession {
            get {
                return ResourceManager.GetString("TitleSaveOrphanSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Extension Folder.
        /// </summary>
        public static string TitleSelectExtensionFolder {
            get {
                return ResourceManager.GetString("TitleSelectExtensionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters Progress.
        /// </summary>
        public static string ToolTipCharsProgress {
            get {
                return ResourceManager.GetString("ToolTipCharsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session HeatMap.
        /// </summary>
        public static string ToolTipHeatMap {
            get {
                return ResourceManager.GetString("ToolTipHeatMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to Audio.
        /// </summary>
        public static string ToolTipPlayAudio {
            get {
                return ResourceManager.GetString("ToolTipPlayAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Played Progress.
        /// </summary>
        public static string ToolTipTimeProgress {
            get {
                return ResourceManager.GetString("ToolTipTimeProgress", resourceCulture);
            }
        }
    }
}
