//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VN2Anki.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VN2Anki.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END SESSION.
        /// </summary>
        public static string BtnEndSession {
            get {
                return ResourceManager.GetString("BtnEndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HISTORY.
        /// </summary>
        public static string BtnHistory {
            get {
                return ResourceManager.GetString("BtnHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERLAY.
        /// </summary>
        public static string BtnOverlay {
            get {
                return ResourceManager.GetString("BtnOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECORD.
        /// </summary>
        public static string BtnRecord {
            get {
                return ResourceManager.GetString("BtnRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE AND CLOSE.
        /// </summary>
        public static string BtnSaveClose {
            get {
                return ResourceManager.GetString("BtnSaveClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START BUFFER.
        /// </summary>
        public static string BtnStartBuffer {
            get {
                return ResourceManager.GetString("BtnStartBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP BUFFER.
        /// </summary>
        public static string BtnStopBuffer {
            get {
                return ResourceManager.GetString("BtnStopBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anki.
        /// </summary>
        public static string HeaderAnki {
            get {
                return ResourceManager.GetString("HeaderAnki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string HeaderConfig {
            get {
                return ResourceManager.GetString("HeaderConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string HeaderControls {
            get {
                return ResourceManager.GetString("HeaderControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Field:.
        /// </summary>
        public static string LblAudioField {
            get {
                return ResourceManager.GetString("LblAudioField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Source:.
        /// </summary>
        public static string LblAudioSource {
            get {
                return ResourceManager.GetString("LblAudioSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck:.
        /// </summary>
        public static string LblDeck {
            get {
                return ResourceManager.GetString("LblDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Dynamic Timeout (Recommended).
        /// </summary>
        public static string LblDynamicTimeout {
            get {
                return ResourceManager.GetString("LblDynamicTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Field:.
        /// </summary>
        public static string LblImageField {
            get {
                return ResourceManager.GetString("LblImageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Type:.
        /// </summary>
        public static string LblNoteType {
            get {
                return ResourceManager.GetString("LblNoteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings on Startup.
        /// </summary>
        public static string LblOpenSettingsOnStartup {
            get {
                return ResourceManager.GetString("LblOpenSettingsOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Limit:.
        /// </summary>
        public static string LblSlotLimit {
            get {
                return ResourceManager.GetString("LblSlotLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (s):.
        /// </summary>
        public static string LblTimeout {
            get {
                return ResourceManager.GetString("LblTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Source:.
        /// </summary>
        public static string LblVideoSource {
            get {
                return ResourceManager.GetString("LblVideoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string MsgAttention {
            get {
                return ResourceManager.GetString("MsgAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Updated!.
        /// </summary>
        public static string MsgCardUpdated {
            get {
                return ResourceManager.GetString("MsgCardUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End current session? Unsent slots will be lost..
        /// </summary>
        public static string MsgConfirmEndSession {
            get {
                return ResourceManager.GetString("MsgConfirmEndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty!.
        /// </summary>
        public static string MsgEmpty {
            get {
                return ResourceManager.GetString("MsgEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR!.
        /// </summary>
        public static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media added successfully!.
        /// </summary>
        public static string MsgSuccess {
            get {
                return ResourceManager.GetString("MsgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready and connected to Anki..
        /// </summary>
        public static string StatusAnkiConnected {
            get {
                return ResourceManager.GetString("StatusAnkiConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anki not detected..
        /// </summary>
        public static string StatusAnkiError {
            get {
                return ResourceManager.GetString("StatusAnkiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing media....
        /// </summary>
        public static string StatusPreparing {
            get {
                return ResourceManager.GetString("StatusPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready. Configure sources and start buffer..
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Running....
        /// </summary>
        public static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ended and memory cleared..
        /// </summary>
        public static string StatusSessionEnded {
            get {
                return ResourceManager.GetString("StatusSessionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Stopped..
        /// </summary>
        public static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }
    }
}
